### ISSUE TITLE
Replace in Delphi (At least for me) is Ctrl + R

### ISSUE THREAD

**Issue by mWaltari** [alefragnani/vscode-delphi-keybindings#2]
I wish it would be same as in Delphi. Not super big deal but I am used to Ctrl+R, not Ctrl+H

**Comment by checkdigits** [comment]
It's CTRL+R for me too using default key bindings. 😁

**Comment by alefragnani** [comment]
I'm pretty sure I also used (and prefer) `Ctrl + R` sometimes 😁, but at some point _at home_, it was showing `Ctrl + H`, that's why the extension was created with it. At least the current install (10.2 Starter) is `Ctrl + R`, but `Ctrl + H` also works 😕 .

Looking at [actual Delphi documentation](http://docwiki.embarcadero.com/RADStudio/Rio/en/Default_Keyboard_Shortcuts) you can understand the mess 

![image](https://user-images.githubusercontent.com/3781424/51491092-6ea23400-1d94-11e9-9571-a92bec310678.png)

Anyway, the _other_ `Ctrl + H` command in Delphi will never _conflict_ with VS Code, because there is no DFM viewer in VS Code, so updating the Replace command to `Ctrl + R` is ok 👍  . Also, `Ctrl + H` is already de default `Search and Replace` shortcut for VS Code.

Thanks for reporting
